#!/bin/bash

main() {
  if get_overlay_now; then
    echo "Already mounted as RO" >&2
  else
    echo "Starting to place root and boot filesystems into read-only mode"
    enable_overlayfs
    sed -i "s/vfat    defaults    /vfat    defaults,ro /" /etc/fstab
    reboot
  fi
}

trap 'main' EXIT

source raspi-config nonint
